// Données utilisateur
export const initialUser = {
  firstName: "Mohammed",
  lastName: "mensori",
  phone: "+212 6 12 34 56 78",
  address: "andaloss,123,Oujda,Maroc",
  gender: "male",
  dob: "2001-06-15",
  avatar: null,
};

export const initialPrivate = {
  email: "mohammed.mes@gmail.com",
  password: "",
  confirmPassword: "",
};

export const stats = [
  { label: "Commandes", value: 12 },
  { label: "Avis", value: 8 },
  { label: "Listes", value: 2 },
  { label: "Note moy.", value: "4.2" },
];

export const genderOptions = [
  { value: "female", label: "Femme" },
  { value: "male", label: "Homme" },
];

// Commentaires simulés
export const mockComments = [
  {
    id: 1,
    productName: "Smartphone Samsung Galaxy S23",
    productImage: "https://via.placeholder.com/60",
    rating: 5,
    comment: "Excellent téléphone ! La batterie tient vraiment bien et l'appareil photo est incroyable. Je recommande vivement.",
    date: "2024-02-15",
    likes: 12,
    verified: true,
  },
  {
    id: 2,
    productName: "Casque Audio Bluetooth Sony WH-1000XM4",
    productImage: "https://via.placeholder.com/60",
    rating: 4,
    comment: "Très bonne qualité sonore, réduction de bruit efficace. Seul bémol : un peu lourd pour les longues sessions.",
    date: "2024-02-10",
    likes: 8,
    verified: true,
  },
  {
    id: 3,
    productName: "Montre Connectée Apple Watch Series 8",
    productImage: "https://via.placeholder.com/60",
    rating: 5,
    comment: "Parfaite pour le suivi sportif et la santé. L'écran est magnifique et les fonctionnalités sont nombreuses.",
    date: "2024-02-05",
    likes: 15,
    verified: true,
  },
  {
    id: 4,
    productName: "Sac à Dos Ordinateur 15 pouces",
    productImage: "https://via.placeholder.com/60",
    rating: 3,
    comment: "Sac correct mais les fermetures éclair semblent fragiles. Je verrai dans la durée.",
    date: "2024-01-28",
    likes: 3,
    verified: false,
  },
  {
    id: 5,
    productName: "Lampe de Bureau LED Rechargeable",
    productImage: "https://via.placeholder.com/60",
    rating: 4,
    comment: "Bon éclairage, plusieurs modes disponibles. L'autonomie est satisfaisante.",
    date: "2024-01-20",
    likes: 5,
    verified: true,
  },
  {
    id: 6,
    productName: "Machine à Café Nespresso Vertuo",
    productImage: "https://via.placeholder.com/60",
    rating: 5,
    comment: "Excellent achat ! Le café est délicieux et la machine très facile à utiliser.",
    date: "2024-01-15",
    likes: 21,
    verified: true,
  },
  {
    id: 7,
    productName: "Enceinte Bluetooth JBL Flip 6",
    productImage: "https://via.placeholder.com/60",
    rating: 4,
    comment: "Bon son, portable, résiste à l'eau. Parfaite pour la plage !",
    date: "2024-01-10",
    likes: 9,
    verified: true,
  },
  {
    id: 8,
    productName: "Livre: Le Guide du Développeur React",
    productImage: "https://via.placeholder.com/60",
    rating: 5,
    comment: "Excellent livre pour apprendre React, bien structuré avec des exemples concrets.",
    date: "2024-01-05",
    likes: 7,
    verified: false,
  },
  {
    id: 9,
    productName: "Adaptateur secteur universel",
    productImage: "https://via.placeholder.com/60",
    rating: 2,
    comment: "Ne fonctionne pas avec tous mes appareils, déçu de la compatibilité.",
    date: "2023-12-28",
    likes: 1,
    verified: true,
  },
  {
    id: 10,
    productName: "Câble USB-C rapide 2m",
    productImage: "https://via.placeholder.com/60",
    rating: 4,
    comment: "Bonne qualité, charge rapide effectivement. Le câble est solide.",
    date: "2023-12-20",
    likes: 4,
    verified: true,
  },
  {
    id: 11,
    productName: "Souris Gaming Logitech G502",
    productImage: "https://via.placeholder.com/60",
    rating: 5,
    comment: "La meilleure souris que j'ai jamais eue ! Précise, confortable, personnalisable.",
    date: "2023-12-15",
    likes: 18,
    verified: true,
  },
  {
    id: 12,
    productName: "Clavier Mécanique RGB",
    productImage: "https://via.placeholder.com/60",
    rating: 4,
    comment: "Bon clavier, touches agréables. Les LEDs sont un peu trop vives à mon goût.",
    date: "2023-12-10",
    likes: 6,
    verified: true,
  },
  {
    id: 13,
    productName: "Support Téléphone Voiture",
    productImage: "https://via.placeholder.com/60",
    rating: 3,
    comment: "Tient bien mais difficile à installer correctement.",
    date: "2023-12-05",
    likes: 2,
    verified: false,
  },
  {
    id: 14,
    productName: "Batterie Externe 20000mAh",
    productImage: "https://via.placeholder.com/60",
    rating: 5,
    comment: "Grosse capacité, recharge plusieurs fois mon téléphone. Indispensable en voyage.",
    date: "2023-11-28",
    likes: 11,
    verified: true,
  },
  {
    id: 15,
    productName: "Écran PC 27 pouces 4K",
    productImage: "https://via.placeholder.com/60",
    rating: 5,
    comment: "Image magnifique, couleurs précises. Parfait pour le travail créatif.",
    date: "2023-11-20",
    likes: 14,
    verified: true,
  },
  {
    id: 16,
    productName: "Webcam Logitech C920",
    productImage: "https://via.placeholder.com/60",
    rating: 4,
    comment: "Bonne qualité d'image pour le télétravail. Le micro est correct.",
    date: "2023-11-15",
    likes: 5,
    verified: true,
  },
  {
    id: 17,
    productName: "Disque Dur Externe 2To",
    productImage: "https://via.placeholder.com/60",
    rating: 5,
    comment: "Rapide, fiable, format compact. Parfait pour les sauvegardes.",
    date: "2023-11-10",
    likes: 8,
    verified: true,
  },
  {
    id: 18,
    productName: "Lampe Torche LED Puissante",
    productImage: "https://via.placeholder.com/60",
    rating: 4,
    comment: "Très puissante, éclaire loin. Les piles s'épuisent vite par contre.",
    date: "2023-11-05",
    likes: 3,
    verified: false,
  },
  {
    id: 19,
    productName: "Balance Connectée",
    productImage: "https://via.placeholder.com/60",
    rating: 3,
    comment: "Fonctionne bien mais l'application est un peu lente.",
    date: "2023-10-28",
    likes: 2,
    verified: true,
  },
  {
    id: 20,
    productName: "Cafetière à Pression",
    productImage: "https://via.placeholder.com/60",
    rating: 5,
    comment: "Excellent café, facile à utiliser. Design élégant.",
    date: "2023-10-20",
    likes: 7,
    verified: true,
  },
];