@UserProfileService_HostAddress = http://localhost:5008
@AuthService_HostAddress = http://localhost:5001/api/auth




###
POST {{AuthService_HostAddress}}/login
Content-Type: application/json

{
  "email": "c@gmail.com",
  "password": "123"
}
###
GET https://www.google.com