@CartService_HostAddress = http://localhost:5003/api/cart
@AuthService_HostAddress = http://localhost:5001/api/auth
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkOWRhMzhhZi0yNWUwLTQ1NjEtYjFhNC01YTE0MTM3NDcyNjgiLCJlbWFpbCI6ImVsbWFsa2lAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJqdGkiOiJlZjMzMjVlYS1mMWRmLTRjZTItYWM2OS0zNDFkN2VjODA2NGIiLCJleHAiOjE3NzI2ODI1NjEsImlzcyI6IkF1dGhTZXJ2aWNlIiwiYXVkIjoiRWNvbW1lcmNlVXNlcnMifQ.aF68ewpcf4Ao_Mi_cxS5EMH8V5T0GbbhHQNfRcUz7bI

### Login to get JWT Token - Done
POST {{AuthService_HostAddress}}/login
Content-Type: application/json

{
  "email": "elmalki@gmail.com",
  "password": "123"
}

### Get User Cart - Done
GET {{CartService_HostAddress}}/getCart
Authorization: Bearer {{token}}
Content-Type: application/json

### Add Item to Cart - Done 
POST {{CartService_HostAddress}}/addToCart
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "productId": 4,
    "stock": 5
}

### Update Item Quantity - Half_Done ( Issue Is I Can Update Above The Max )
PUT {{CartService_HostAddress}}/updateStock
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "productId": 6,
    "stock": 2000
}

### Delete Item from Cart - Done
DELETE {{CartService_HostAddress}}/deleteItem/1
Authorization: Bearer {{token}}
Content-Type: application/json

### Clear Entire Cart - Done
POST {{CartService_HostAddress}}/clearCart
Authorization: Bearer {{token}}
Content-Type: application/json